# Configurazione del laboratorio 04 — Fault Tolerance
#
# TODO: Implementare qui i parametri di Fault Tolerance, se scegli di
# configurarli da file invece che nelle annotazioni. Esempi di chiavi:
#
# io.github.marcotondi.labs.faulttolerance.PriceService/getQuote/Timeout/value=200
# io.github.marcotondi.labs.faulttolerance.PriceService/getPrice/Retry/maxRetries=3

quarkus.log.category."io.github.marcotondi.labs.faulttolerance".level=INFO