# Configurazione del laboratorio 07 — Metrics (Micrometer)
# L'endpoint delle metriche è esposto di default su /q/metrics.
# TODO: Implementare qui eventuali configurazioni delle metriche, se servono.

quarkus.micrometer.export.prometheus.enabled=true